services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotjeletotnewsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hotjeletotnews-network
    ports:
      - "5432:5432"
  
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Gunakan nama service 'db' sebagai host
      DATABASE_URL: "postgres://user:password@db:5432/hotjeletotnewsdb"
      NODE_ENV: "production"
    networks:
      - hotjeletotnews-network

networks:
  hotjeletotnews-network:
    driver: bridge
volumes:
  postgres-data:
